# This file was generated by GoReleaser. DO NOT EDIT.
cask "kbark" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "8516381313413ff6c94f87f9cdcc182f3eeb522e0d349e92044ed02eba8d7a3b"
      url "https://github.com/shivangtanwar/kbark/releases/download/v#{version}/kbark_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c53fa66f726bf48fb70ad42a4c29a393adb26818271c95e6e63fe140043cc5c5"
      url "https://github.com/shivangtanwar/kbark/releases/download/v#{version}/kbark_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e10f2000f6236aedfbb848743440ba9391613d805e93fcc913d46aab5df750ee"
      url "https://github.com/shivangtanwar/kbark/releases/download/v#{version}/kbark_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ba5d67bcbea0b12f5d3dd4b041a026992ab33d92c791795d0eaf3478be556b8"
      url "https://github.com/shivangtanwar/kbark/releases/download/v#{version}/kbark_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kbark"
  desc "Kubernetes terminal UI with an AI on the ? key"
  homepage "https://kbark.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kbark"

  # No zap stanza required

end
