# This file was generated by GoReleaser. DO NOT EDIT.
cask "kbark" do
  version "0.1.0-rc2"

  on_macos do
    on_intel do
      sha256 "589a9ac488a6fc5cfe29eff49451f1df98f26e0b6c61f10d33b7a9cb19b4c764"
      url "https://github.com/shivangtanwar/kbark/releases/download/v#{version}/kbark_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0da76d5213aa090bdc7777e8169cf410c2fd9251b7e4977145050c6584f0f135"
      url "https://github.com/shivangtanwar/kbark/releases/download/v#{version}/kbark_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0a359ec0bbc611649637eafa598ab57e8f0441707754cbe1425cea50e21a423a"
      url "https://github.com/shivangtanwar/kbark/releases/download/v#{version}/kbark_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e766870d5b0f6a44b47a9ec7281326d77f11d8f353055f8b20b69d17d365f278"
      url "https://github.com/shivangtanwar/kbark/releases/download/v#{version}/kbark_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kbark"
  desc "Kubernetes terminal UI with an AI on the ? key"
  homepage "https://kbark.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kbark"

  # No zap stanza required

end
